Evolveum/midpoint

dist/pom.xml
Hello,
I have found same problem in v3.1. After this you don't have to take care about version of prism and schema .
cheers
My v3.1 stack trace 
```
[ERROR] Failed to execute goal com.evolveum.midpoint.tools:schema-dist-maven-plugin:3.1:schemadist (schemadist-prism) on project dist: Error resolving artifact com.evolveum.midpoint.infra:prism:jar:3.1-SNAPSHOT:compile: Failure to find com.evolveum.midpoint.infra:prism:jar:3.1-SNAPSHOT in http://nexus.evolveum.com/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of evolveum has elapsed or updates are forced
[ERROR] 
[ERROR] Try downloading the file manually from the project website.
[ERROR] 
[ERROR] Then, install it using the command:
[ERROR] mvn install:install-file …
```
=> bugfix: midPoint Distribution - set correct dependency com.evolveum.midpoint.infra.prism and com.evolveum.midpoint.infra.schema to ${project.version}

gui/admin-gui-cs-CZ/src/main/resources/com/evolveum/midpoint/web/page/login/PageLogin_cs.utf8.properties, gui/admin-gui-cs-CZ/src/main/resources/com/evolveum/midpoint/web/page/login/PageLogin_cs_CZ.utf8.properties
Small repair in CZ lang package.
=> Small repair in CZ lang package.

model/model-impl/src/main/java/com/evolveum/midpoint/model/impl/sync/CorrelationConfirmationEvaluator.java, samples/resources/office365/office365-managed2.xml
Fixed Filter in correlation generates duplicate output (MID-3035), Added O365 example.
=> Fixed Filter in correlation generates duplicate output (MID-3035), Added O365 example.

gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/reports/PageAuditLogViewer.java
fix the error about the table on the audit log viewer page
=> fix the error about the table on the audit log viewer page

build-system/pom.xml, pom.xml, samples/model-client-sample/pom.xml
Also updates the plugin version to be on 3.5.1.
=> Let the maven compiler build midpoint via JDK 8.

model/model-impl/src/main/java/com/evolveum/midpoint/model/impl/lens/projector/DependencyProcessor.java, testing/story/src/test/java/com/evolveum/midpoint/testing/story/TestLdapDependency.java, testing/story/src/test/resources/ldap-dependency/org-top.xml, testing/story/src/test/resources/ldap-dependency/resource-opendj.xml, testing/story/src/test/resources/ldap-dependency/role-meta-org-supervip.xml, testing/story/src/test/resources/ldap-dependency/role-meta-org-vip.xml, testing/story/src/test/resources/ldap-dependency/role-meta-org.xml
=> Support 3.4 test dependencies fix

infra/schema/src/main/resources/xml/ns/public/common/common-notifications-3.xsd, model/notifications-api/src/main/java/com/evolveum/midpoint/notifications/api/transports/Message.java, model/notifications-impl/src/main/java/com/evolveum/midpoint/notifications/impl/api/transports/MailTransport.java, model/notifications-impl/src/main/java/com/evolveum/midpoint/notifications/impl/notifiers/GeneralNotifier.java, samples/objects/extended-notifications.xml
=> add support for html (MID-2072)

gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/configuration/dto/AppenderConfiguration.java, gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/configuration/dto/FileAppenderConfig.java, infra/common/src/main/java/com/evolveum/midpoint/common/LoggingConfigurationManager.java, infra/schema/src/main/resources/xml/ns/public/common/common-core-3.xsd
We needed this to support multiple appenders writing to one destination (which is parsed by SIEM). Feel free to enhance product, if you like.
=> Logging: Prudent RollingFileAppender support (remote & shared files)

infra/common/src/main/java/com/evolveum/midpoint/common/LoggingConfigurationManager.java, infra/prism/src/main/java/com/evolveum/midpoint/prism/lex/json/yaml/MidpointYAMLGenerator.java, infra/prism/src/main/java/com/evolveum/midpoint/prism/marshaller/ItemPathHolder.java, infra/prism/src/main/java/com/evolveum/midpoint/prism/marshaller/TrivialItemPathParser.java, infra/prism/src/main/java/com/evolveum/midpoint/prism/polystring/PrismDefaultPolyStringNormalizer.java, infra/prism/src/main/java/com/evolveum/midpoint/prism/query/ObjectPaging.java, infra/prism/src/main/java/com/evolveum/midpoint/prism/util/PrismPrettyPrinter.java, infra/util/src/main/java/com/evolveum/midpoint/util/DOMUtil.java, infra/util/src/main/java/com/evolveum/midpoint/util/MiscUtil.java, infra/util/src/main/java/com/evolveum/midpoint/util/QNameUtil.java
This is a batch of trivial string handling optimizations.
=> Simple string optimizations

gui/admin-gui/src/main/webapp/less/midpoint-theme.less
Thanks god for stable and fast browser like IE :)
=> MID-4149 (Shopping cart footer overflow fix - IE supported)

gui/admin-gui/src/main/webapp/WEB-INF/ctx-web-security-cas.xml
This fixes the property value to the correct cas login page
=> fix cas login page

infra/prism/src/main/java/com/evolveum/midpoint/prism/polystring/PolyString.java, model/model-common/src/main/java/com/evolveum/midpoint/model/common/expression/functions/BasicExpressionFunctions.java
=> New helper functions: PolyString, normalization and prefix comparisons

build-system/pom.xml
Updated a number of dependencies; Spring and Logback should provide minor performance improvements.
=> Dependency Upgrades - Logback, Spring, etc

weblogic-build/pom.xml
Don't know whether this is the appropriate branch but there a small error in the pom.xml of 3.7.1 which prevents the build from completing.
=> Correct weblogic pom.xml for 3.7.1

testing/story/src/test/java/com/evolveum/midpoint/testing/story/TestReconNullValue.java, testing/story/src/test/resources/recon-null-value/object-template-user.xml, testing/story/src/test/resources/recon-null-value/org-top.xml, testing/story/src/test/resources/recon-null-value/resource-opendj.xml, testing/story/src/test/resources/recon-null-value/role-ldap.xml
Test for MID-4567 (branch support-3.7)
=> Test MID-4567

infra/util/src/main/java/com/evolveum/midpoint/util/DOMUtil.java
DocumentBuilderFactory and Transformer objects are created every time locally for every call and every call-site; These calls produce significant overhead in profiling a running midpoint instance. This PR moves the logic into thread-locals to preserve thread-safety along with some degree of static caching.
=> Performance Improvement - Create DocumentBuilder/Transfomer per thread

gui/admin-gui/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, model/model-impl/src/main/java/com/evolveum/midpoint/model/impl/lens/projector/FocusProcessor.java, model/model-impl/src/main/java/com/evolveum/midpoint/model/impl/sync/SynchronizationServiceImpl.java, model/model-intest/src/test/java/com/evolveum/midpoint/model/intest/TestActivation.java, model/model-test/src/main/java/com/evolveum/midpoint/model/test/AbstractModelIntegrationTest.java
Changes to wildfly support branch
=> Support 3.4 wildfly

gui/admin-gui/src/main/java/com/evolveum/midpoint/web/boot/WebSecurityConfig.java, gui/admin-gui/src/main/resources/application.yml
This change adds support for SSO implementations using environment variable (like Shibboleth, or WebAuth).
There is used request authentication filter from spring security. Details: https://github.com/spring-projects/spring-security/pull/3978
=> SSO profile using environment - Shibboleth, WebAuth

repo/security-api/src/main/java/com/evolveum/midpoint/security/api/AuthorizationConstants.java
I found missing '#' for usersView action URL.
=> Fix usersView action URL

testing/story/src/test/java/com/evolveum/midpoint/testing/story/TestInducement.java, testing/story/src/test/resources/inducement/role-lock.xml, testing/story/src/test/resources/inducement/role-processor.xml, testing/story/src/test/resources/inducement/role-role1.xml, testing/story/src/test/resources/inducement/role-role2.xml, testing/story/src/test/resources/inducement/role-role3.xml, testing/story/src/test/resources/inducement/user-simple.xml
storytest for https://jira.evolveum.com/browse/MID-5366
=> MID-5366 Testinducement

gui/admin-gui/src/main/java/com/evolveum/midpoint/web/boot/MidPointSpringApplication.java
It seems that the session timeout of embedded tomcat doesn't work correctly. It expires only if I do request again after the timeout period although I expect it expires automatically after the period without any operations. So it causes OutOfMemory.
After some investigation, I found that the thread which invalidates timeout sessions doesn't work. To do that, we need to setup `backgroundProcessorDelay` correctly because the default value is `-1`. 
By applying my patch, we can see the expiration work as below when we add logger for `org.apache.catalina.session.ManagerBase` package with `DEBUG` level in SystemConfiguration.
```
2019-09-06 18:24:19,272 [] [ContainerBackgroundProcessor[StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[/midpoint]]] DEBUG …
```
=> Fix tomcat session timeout

infra/prism-impl/src/main/java/com/evolveum/midpoint/prism/impl/xjc/PropertyArrayList.java, infra/prism-impl/src/test/java/com/evolveum/midpoint/prism/TestPropertyArrayList.java, infra/prism-impl/testng-unit.xml
Hi there, i've picked from jira issue [**MID-4404**] and solved it! I've also added unit test for my solution. Alcides Neto can be happy once again since waiting from 22/Jan/18 10:25 PM !
=> Solved issue [MID-4404] + added unit test

model/model-impl/src/main/java/com/evolveum/midpoint/model/impl/scripting/actions/AssignExecutor.java, model/model-intest/src/test/java/com/evolveum/midpoint/model/intest/scripting/TestScriptingBasic.java, model/model-intest/src/test/resources/scripting/assign-to-will-2.xml
https://jira.evolveum.com/browse/MID-6054
Currently, it checks the relation using `RelationTypes.values()` which returns static relations only when executing the assignment.
I switched it to `RelationRegistry#getRelationDefinitions()` to collect static relations + custom relations.
Also, I added a new test case `test394AssignToWill2` for testing assignment with custom relation.
=> MID-6054 Fix assignment with custom relation

gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/configuration/InternalsClockPanel.java, testing/schrodingertest/src/test/java/com/evolveum/midpoint/testing/schrodinger/page/InternalsConfigurationPageTest.java, tools/schrodinger/src/main/java/com/evolveum/midpoint/schrodinger/component/configuration/ClockTab.java, tools/schrodinger/src/main/java/com/evolveum/midpoint/schrodinger/page/BasicPage.java, tools/schrodinger/src/main/java/com/evolveum/midpoint/schrodinger/page/configuration/InternalsConfigurationPage.java
https://jira.evolveum.com/browse/MID-6085
=> MID-6085 fix time change error in Internals configuration page

gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/roles/MemberOperationsHelper.java, gui/admin-gui/src/test/java/com/evolveum/midpoint/gui/TestPageRole.java, gui/admin-gui/src/test/java/com/evolveum/midpoint/web/AbstractGuiIntegrationTest.java, model/model-test/src/main/java/com/evolveum/midpoint/model/test/AbstractModelIntegrationTest.java
https://jira.evolveum.com/browse/MID-6092
=> MID-6092 Fix filtering by orgRef or tenantRef in role members tab

build-system/pom.xml, gui/admin-gui/pom.xml, gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/certification/PageCertDecisions.java, gui/admin-gui/src/main/java/com/evolveum/midpoint/web/session/CertDecisionsStorage.java, gui/admin-gui/src/main/java/com/evolveum/midpoint/web/session/SessionStorage.java
Hi, please approve this backport of MID-6100 to this branch.
It was already talked about with KatkaV
=> MID-6100 - backport to support-3.7

gui/admin-gui/src/main/java/com/evolveum/midpoint/gui/api/util/WebModelServiceUtils.java, gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/login/PageSelfRegistration.java
https://jira.evolveum.com/browse/MID-6154
=> MID-6154 Fix error message to be localized in self registration page

model/notifications-impl/src/main/java/com/evolveum/midpoint/notifications/impl/api/transports/MailTransport.java
https://jira.evolveum.com/browse/MID-6190
=> Mailtransport connection

infra/prism-api/src/main/java/com/evolveum/prism/xml/ns/_public/types_3/PolyStringNormalizerConfigurationType.java
See https://jira.evolveum.com/browse/MID-6348
=> MID-6348 fix missing nfkd

gui/admin-gui/src/main/java/com/evolveum/midpoint/gui/api/GuiStyleConstants.java, gui/admin-gui/src/main/java/com/evolveum/midpoint/gui/api/util/WebComponentUtil.java, gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/resources/PageResource.html, gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/resources/PageResource.java, gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/resources/PageResources.java, gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/resources/ResourceDetailsTabPanel.java, gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/resources/ResourceSummaryPanel.java, gui/admin-gui/src/main/resources/static/less/midpoint-theme.less, model/model-impl/src/main/java/com/evolveum/midpoint/model/impl/lens/projector/ContextLoader.java, provisioning/provisioning-impl/src/main/java/com/evolveum/midpoint/provisioning/impl/ShadowCache.java, testing/story/src/test/java/com/evolveum/midpoint/testing/story/TestResourceInMaintenance.java, testing/story/src/test/resources/resource-in-maintenance/csv-resource1.xml
- GUI Resource detail option: Toggle maintenance
- GUI misc (icon etc..)
- Fixed update after create scenario
- Improved tests
=> Resource maintenance fixes and improvements

infra/prism-impl/src/main/java/com/evolveum/midpoint/prism/impl/crypto/KeyStoreBasedProtectorImpl.java, infra/prism-impl/src/test/java/com/evolveum/midpoint/prism/TestEquals.java
https://jira.evolveum.com/browse/MID-6806
=> MID-6806 fix ProtectedStringType comparison issue

model/model-common/src/main/java/com/evolveum/midpoint/model/common/util/DefaultColumnUtils.java
https://jira.evolveum.com/browse/MID-7070
=> MID-7070 Fix display type of projections column

gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/self/component/DashboardSearchPanel.java
See https://jira.evolveum.com/browse/MID-7131
=> MID-7131 Fix NPE on home page

gui/admin-gui/src/main/java/com/evolveum/midpoint/web/session/SessionStorage.java
See https://jira.evolveum.com/browse/MID-7134
=> MID-7134 Fix NPE in members tab of Archetype page

gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/home/component/SystemInfoPanel.html, gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/home/component/SystemInfoPanel.java, repo/task-api/src/main/java/com/evolveum/midpoint/task/api/TaskManager.java, repo/task-quartz-impl/pom.xml, repo/task-quartz-impl/src/main/java/com/evolveum/midpoint/task/quartzimpl/TaskManagerQuartzImpl.java
Tested on Postgres and H2. Please cherry pick to master.
=> MID-7090: GUI Info Dashboard System status panel - DB connections stats

model/model-impl/src/main/java/com/evolveum/midpoint/model/impl/lens/assignments/ConditionEvaluator.java
and not condtionEvaluator.
need to call assignmentEvaluator.isMemberOf(roleOid) in condition.
=> assignmentEvaluator should contain assignmentEvaluator 

gui/admin-gui/src/main/java/com/evolveum/midpoint/gui/impl/page/admin/resource/component/ResourceConfigurationPanel.java
…ethods in ResourceConfigurationPanel.
=> Added Spelling Corrections to ResourceConfigurationPanel

gui/admin-gui/src/main/java/com/evolveum/midpoint/web/security/MidPointApplication.java, gui/admin-gui/src/main/java/com/evolveum/midpoint/web/security/WicketConfigurator.java, gui/admin-gui/src/main/java/com/evolveum/midpoint/web/security/WicketNoSerializationConfigurator.java
This is a pull request to apply the same modifications to `support-4.4` branch as #167.
=> MID-7135 Add no-serialization option for Wicket (for support-4.4 branch)

repo/repo-sqale/src/test/java/com/evolveum/midpoint/repo/sqale/func/SqaleRepoSearchTest.java, repo/repo-sqlbase/src/main/java/com/evolveum/midpoint/repo/sqlbase/filtering/item/ItemValueFilterProcessor.java
See https://jira.evolveum.com/browse/MID-8005
=> MID-8005 Fixed "stringIgnoreCase" matching rule without namespace does not work

gui/admin-gui/src/main/java/com/evolveum/midpoint/web/component/search/Search.java
https://jira.evolveum.com/browse/MID-8400 for support-4.4 branch.
=> MID-8400 Fixed date search from GUI not being ge/le search (for support-4.4 branch)

gui/admin-gui/src/main/java/com/evolveum/midpoint/gui/api/page/PageAdminLTE.java, gui/admin-gui/src/main/java/com/evolveum/midpoint/web/boot/MidPointSpringApplication.java, gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/certification/CertDecisionHelper.java, gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/certification/handlers/CertGuiHandlerRegistry.java, gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/certification/handlers/DirectAssignmentCertGuiHandler.java, gui/admin-gui/src/test/java/com/evolveum/midpoint/gui/test/TestMidPointSpringApplication.java
https://jira.evolveum.com/browse/MID-8796
=> MID-8796 Fixed Custom CertificationHandler not working

gui/admin-gui/src/main/java/com/evolveum/midpoint/gui/api/page/PageBase.java, gui/admin-gui/src/main/java/com/evolveum/midpoint/web/boot/MidPointSpringApplication.java, gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/certification/CertDecisionHelper.java, gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/certification/handlers/CertGuiHandlerRegistry.java, gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/certification/handlers/DirectAssignmentCertGuiHandler.java, gui/admin-gui/src/test/java/com/evolveum/midpoint/gui/test/TestMidPointSpringApplication.java
https://jira.evolveum.com/browse/MID-8796
=> MID-8796 Fixed Custom CertificationHandler not working (for support-4.4)

gui/admin-gui/src/main/java/com/evolveum/midpoint/gui/api/util/WebComponentUtil.java
See https://jira.evolveum.com/browse/MID-8932
=> MID-8932 Fix NPE when displaying Attributes tab in resource definition (for support-4.4)

model/certification-impl/src/main/java/com/evolveum/midpoint/certification/impl/AccCertQueryHelper.java
**What**
Use non iterative search, if the repository isn't "native"
**Why**
Iterative search is not implemented in "non native" repositories (i.e. the old repository which uses Hibernate). Using iterative search on those repositories caused an exception.
**Fixes:** MID-10225
=> Fix certifications for non-native repo

docs/security/authentication/administrator-initial-password.adoc
Add more information on how to set the initial password, where to get it when it auto-generates, ammend the rules for passwords
=> improve initial admin psw docs

docs/schema/archetypes/configuration.adoc, docs/tasks/shadow-reclassification-task/index.adoc
convert GUI guide links to TIP admonition blocks; add GUI guide link to shadow reclassification XML guide; slightly shorten/improve wording of the GUIde promo  and make it universal / more easily reusable
=> remake GUIde links to admonitions; add GUIde link to shadow reclass. XML guide

docs/admin-gui/resource-wizard/object-type/index.adoc
I removed Ivan's comment about the need for a delineation article link as I've added such a link (couple of them, actually) previously and just waited for vix to confirm they're what he had in mind. I now have the confirmation so I removed the comment. Related WP: https://support.evolveum.com/wp/9404 I also linked the shadow reclassification GUIde which is relevant but didn't exist before.
BTW, sorry for the screwed up branch name -__-
=> Remove resolved comment; add reclassification link

docs/roles-policies/identity-governance-rules/index.adoc
remove version specification from the link to avoid 404
=> fix reference link

docs/expressions/mappings/index.adoc
[.nowrap]#.........# 
used for table items not to wrap.
=> nowrap added to mappings table

docs/admin-gui/resource-wizard/association-type/index.adoc, docs/admin-gui/resource-wizard/association-type/subject/index.adoc, docs/admin-gui/resource-wizard/association-type/subject/provisioning-from-resource/index.adoc, docs/admin-gui/resource-wizard/association-type/subject/provisioning-to-resource/index.adoc, docs/admin-gui/resource-wizard/object-type/activation/index.adoc, docs/admin-gui/resource-wizard/object-type/capability/index.adoc, docs/admin-gui/resource-wizard/object-type/credentials/index.adoc, docs/admin-gui/resource-wizard/object-type/index.adoc, docs/admin-gui/resource-wizard/object-type/mapping/advanced-mappings.adoc, docs/admin-gui/resource-wizard/object-type/mapping/index.adoc, docs/admin-gui/resource-wizard/object-type/policies/index.adoc, docs/admin-gui/resource-wizard/object-type/synchronization/index.adoc, docs/admin-gui/resource-wizard/wizard-existing-resource/index.adoc, docs/admin-gui/role-wizard/index.adoc, docs/schema/archetypes/configuration-gui/archetypes-in-object-type-wizard.adoc, docs/schema/archetypes/configuration-gui/index.adoc, docs/schema/archetypes/person.adoc, docs/schema/custom-schema-extension/changing-schema-extension-via-GUI/index.adoc, docs/tasks/shadow-reclassification-task/gui.adoc
Remove links from images because they no longer make sense - we have the lightbox now - https://github.com/Evolveum/evolveum-jekyll/pull/4
=> Remove links from images
