Evolveum/midpoint

infra/prism/src/main/java/com/evolveum/prism/xml/ns/_public/types_3/ItemDeltaType.java

We have found error that similar RawType-objects doesn't equlas. 
The reason is in getParsedValue. After we've got an parsed value and generating Delta with "origin" value (readed from DB) equals return false, even raw object haven't been changed.
Than we try to clone the origin object - it doesn't help because list of raw object doesn't clone and only copiies.
It kills three weeks of my work time..

patching clone method

---

.gitignore
build-system/pom.xml
gui/admin-gui/pom.xml

- Fix minor formatting issues in the pom
- Let the admin gui (i.e midpoint.war) to be deployed via an embedded jetty instance. (Would have done the same for Tomcat, except tomcat plugins are terrible)
Basically, you'd do this:
```
cd midpoint/gui/admin-gui
mvn jetty:run-forked
```
Then go to `localhost:8080/midpoint` and login. 
Don't ask developers to download a separate tomcat instance to test. More work for them :)

Run admin-gui web pp with an embedded jetty

---

testing/story/src/test/java/com/evolveum/midpoint/testing/story/TestLdapDependency.java
testing/story/src/test/resources/ldap-dependency/org-top.xml
testing/story/src/test/resources/ldap-dependency/resource-opendj.xml
testing/story/src/test/resources/ldap-dependency/role-meta-org-supervip.xml
testing/story/src/test/resources/ldap-dependency/role-meta-org-vip.xml
testing/story/src/test/resources/ldap-dependency/role-meta-org.xml

having two similar roles for orgs each containing two inducements:
one for creating org unit in ldap, one for creating group in ldap. each group depends on org unit of the same role.
when both roles are assigned and one is removed midpoint fails complaining about dependency.
but this should not happen since group2 does not depend on anything of role1.

test dependencies

---

config/sql/_all/postgresql-3.5-all.sql

PostgreSQL does not create automatic indexes on foreign key columns.
Delete from parent table is very slow because of full scan on the record_id columns of the child tables.

Added indexes on m_audit_item(record_id) and m_audit_delta(record_id)

---

gui/admin-gui/src/main/java/com/evolveum/midpoint/web/component/form/multivalue/MultiValueChoosePanel.java
gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/reports/component/ConvertingMultiValueChoosePanel.java

Selecting targets in Audit Log Viewer popup object browser and pressing 'Add' now only adds the selected values instead of replacing the old list. This way you can even select multiple targets of different types for audit.

Multi value target - changed target Edit do Add

---

build-system/pom.xml
infra/schema-pure-jaxb/pom.xml
model/model-client/pom.xml
pom.xml
samples/model-client-sample/pom.xml
testing/minipoint/pom.xml

Opt for a "more secure" option to load/download artifacts from the nexus repository.

Load artifacts from repository under https rather than http

---

gui/admin-gui/src/main/java/com/evolveum/midpoint/gui/api/page/PageBase.java

After this change you can now use `<headerColor/>`  in tandem with `<skin/>`. If skin is populated, the skins header color will apply to the main header bar, but if headerColor is also populated, it will apply to the left side around the image. This is useful for example, if you also need to use a logo with a solid white background, but want to also use an alternate skin. The example below shows a more extreme contrast for illustration purposes. 
```
<deploymentInformation>
<name>TEST</name>
<headerColor>red</headerColor>
<skin>skin-green-light</skin>
</deploymentInformation>
```

Prevents gui color conflict between headerColor and skin colors

---

gui/admin-gui/src/main/java/com/evolveum/midpoint/web/component/input/StringChoiceRenderer.java
gui/admin-gui/src/main/java/com/evolveum/midpoint/web/component/wizard/resource/component/schemahandling/modal/MappingEditorDialog.java
gui/admin-gui/src/main/java/com/evolveum/midpoint/web/component/wizard/resource/component/synchronization/SynchronizationReactionEditor.java
gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/configuration/PageAccounts.java
gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/configuration/component/LoggingConfigPanel.java
gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/reports/PageCreatedReports.java
gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/server/PageTaskAdd.java
gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/server/PageTasks.java

This class is used in three distinct cases:
- no prefix at all
- with a prefix
- with a prefix and a split pattern
Refactor each case into a separate subclass and expose them
via static factory methods. This allows for smaller footprint
and more direct execution paths, as well as sharing a single object
for the non-prefixed case.
Users are updated to account for the split and to reuse instances
where possible.
Signed-off-by: Robert Varga <nite@hq.sk>

Refactor StringChoiceRenderer

---

gui/admin-gui/src/main/webapp/less/midpoint-theme.less

This minor style-sheet change improve "add-to-cart" button overflow (please see MID-4149 for more info)

MID-4149 (shopping cart footer add button float fix)

---

testing/story/src/test/java/com/evolveum/midpoint/testing/story/TestLdapVirtualGroup.java
testing/story/src/test/resources/ldap-virtualgroup/org-top.xml
testing/story/src/test/resources/ldap-virtualgroup/resource-opendj.xml
testing/story/src/test/resources/ldap-virtualgroup/role-it-hr-thisobject.xml
testing/story/src/test/resources/ldap-virtualgroup/role-it-hr.xml
testing/story/src/test/resources/ldap-virtualgroup/role-jobrole-devops.xml
testing/story/src/test/resources/ldap-virtualgroup/role-jobrole-multijobs.xml
testing/story/src/test/resources/ldap-virtualgroup/role-meta-ldap-thisobject.xml
testing/story/src/test/resources/ldap-virtualgroup/role-meta-ldap.xml

This test uses OpenDJs virtual-attributes to manage group membership.
there is no error, would be nice to see it in storytest to ensure functionalitiy in future releases.
An other topic I tried to handle using this test is the replacement of the thisObject variable.
so far in the metarole and the "normal" role $thisObject can be used to fetch the required name.
In metaroles this can be replaced by "$mmediateRole, in normal roles by $source, but I have o idea how find same replacement for all roletypes (using assignementPath as proposed in WIKI??). (see role-meta-ldap.xml and role-it-hr.xml)

Testvirtualgroup / replace thisObject

---

provisioning/provisioning-impl/src/main/java/com/evolveum/midpoint/provisioning/util/ProvisioningUtil.java

SelectorOptions retrieval settings currently influences only several hardcoded attributes (see blocks of code labeled by comments Password, Activation etc.). With this change attributes with minimal fetch strategy will not be in the list given to the connector by default, but can be turned on by setting their selector option retrieval to INCLUDE.

Make SelectorOptions modify list of fetched attrs

---

infra/common/src/main/java/com/evolveum/midpoint/common/refinery/LayerRefinedAttributeDefinitionImpl.java

The hashCode breaks equals contract by calling super.hashCode() which is java.lang.Object.hashCode().
This was breaking ExpressionFactory.cache key hashCode causing the cache to grow indefinitely.

Fixed hashCode in LayeredRefinedAttributeDefinitionImpl

---

gui/admin-gui/src/main/java/com/evolveum/midpoint/web/component/DropDownMultiChoice.java
gui/admin-gui/src/main/java/com/evolveum/midpoint/web/security/MidPointApplication.java
infra/prism/src/main/java/com/evolveum/midpoint/prism/marshaller/ItemPathHolder.java
infra/prism/src/main/java/com/evolveum/midpoint/prism/xml/XsdTypeMapper.java
infra/util/src/main/java/com/evolveum/midpoint/util/aspect/ProfilingDataManager.java
model/model-common/src/main/java/com/evolveum/midpoint/model/common/stringpolicy/ValuePolicyProcessor.java
model/notifications-impl/src/main/java/com/evolveum/midpoint/notifications/impl/api/transports/MailTransport.java
tools/xjc-plugin/src/main/java/com/evolveum/midpoint/schema/xjc/schema/SchemaProcessor.java

A number of map iterations access values using a key fetched from keySet. Using entrySet is more efficient, in order to avoid get(key) lookups later.

Optimize map iterations using entrySet()

---

model/model-impl/src/main/java/com/evolveum/midpoint/model/impl/lens/Clockwork.java

I found tons of log messages
(com.evolveum.midpoint.model.impl.lens.Clockwork): Couldn't record operation execution. Model context:
...
caused by
java.lang.IllegalArgumentException: fromIndex(0) > toIndex(-1)
at java.util.ArrayList.subListRangeCheck(ArrayList.java:1006)
at java.util.ArrayList.subList(ArrayList.java:996)
at com.evolveum.midpoint.model.impl.lens.Clockwork.storeOperationExecution(Clockwork.java:883)
The array in the condition was no longer the same as the array in subList call, there may be items deleted just two lines above.

Fixed Couldn't record operation execution

---

gui/admin-gui/src/main/java/com/evolveum/midpoint/web/boot/WebSecurityConfig.java

Although midPoint has `sso` profile, it doesn't work. I improved the following points.
- Fix `AuthenticationManager` injection
- Adjust RequestHeaderAuthenticationFilter order
- Add an option for changing the SSO header name

Improve sso profile

---

repo/repo-sql-impl/src/main/java/com/evolveum/midpoint/repo/sql/SqlAuditServiceImpl.java

Same hack as for mysql added for postgresql.
Necessary audit indexes in postgre init scripts are already ok.

Fixed deleting audit events from large audit database on postgresql

---

infra/prism/src/main/java/com/evolveum/midpoint/prism/delta/ContainerDelta.java

This fixes the "Conflicting modification in delta" exceptions  when delta has no modifications in conflict. If this change makes sense, please port to 3.8 and master as well.
TLDR Preparing mapping source values with paths into containers that are created or modified in the current object delta by multiple non-conflicting modifications could lead to 'Conflicting modification in delta'. I belive the problem is ContainerDelta.findItemValues treats empty collection ItemDelta as empty while ItemDelta.isEmpty thinks otherwise.
To save you an ugly debugging session and justify my change, here is the long story:
Test case is changing users password for the first time - midpoint creates one modification for credentials/password/value and another for credentials/password/metadata in the object …

fix Conflicting modification in delta exceptions

---

model/model-impl/src/main/java/com/evolveum/midpoint/model/impl/lens/AssignmentPathImpl.java

When using negative assignmentPathIndex, it always causes `IndexOutOfBoundsException`.

Fix handling negative assignmentPathIndex

---

gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/PageAdminObjectDetails.java

This is very small PR, but it helps creating subtype-specific new object form. 
For example, when we define custom form using object templates for two subtype of UserType like `permanent` and `temporary`, we can open the new page using below links. Also we can define these links as additionalMenuLink or additionalMenuLink in adminGuiConfiguration. It's very useful. 
* /admin/user?subtype=permanent
* /admin/user?subtype=temporary

Apply subtype using page parameter when accessing new object page

---

gui/admin-gui/src/main/resources/static/less/midpoint-theme.less

I noticed [MID-4867](https://jira.evolveum.com/browse/MID-4867) 5 (Number icon in new shopping cart position is misplaced in Firefox) is also occurring in other browsers (Chrome, IE11 with IE9 mode).
I think the css style should be applied to all browsers.

Fix MID-4867 5 for all browsers

---

infra/test-util/src/main/java/com/evolveum/midpoint/test/util/DerbyController.java

When running the tests I encountered a timing issue where the derby server was not ready and a connection was being established resulting in a connection failure. This fix waits until the server pings back before continuing the test.

make the start method wait until the debry server is accesible

---

gui/admin-gui/src/main/java/com/evolveum/midpoint/gui/api/util/WebComponentUtil.java

Although we can localize labels in lookupTable, it only looks message bundle of the default locale. Login users can't see the localized labels if they switched the preferred language.

MID-6030 fix lookupTable localization to use session locale

---

gui/admin-gui/src/main/java/com/evolveum/midpoint/gui/api/GuiStyleConstants.java
gui/admin-gui/src/main/java/com/evolveum/midpoint/gui/api/util/WebComponentUtil.java
gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/resources/ResourceSummaryPanel.java
gui/admin-gui/src/main/resources/static/less/midpoint-theme.less
infra/schema/src/main/java/com/evolveum/midpoint/schema/util/ResourceTypeUtil.java
infra/schema/src/main/resources/xml/ns/public/common/common-core-3.xsd
infra/util/src/main/java/com/evolveum/midpoint/util/exception/MaintenanceException.java
model/model-impl/src/main/java/com/evolveum/midpoint/model/impl/lens/LensProjectionContext.java
model/model-impl/src/main/java/com/evolveum/midpoint/model/impl/util/ModelImplUtils.java
provisioning/provisioning-impl/src/main/java/com/evolveum/midpoint/provisioning/impl/ProvisioningServiceImpl.java
provisioning/provisioning-impl/src/main/java/com/evolveum/midpoint/provisioning/impl/ShadowCache.java
provisioning/provisioning-impl/src/main/java/com/evolveum/midpoint/provisioning/impl/errorhandling/ErrorHandlerLocator.java
provisioning/provisioning-impl/src/main/java/com/evolveum/midpoint/provisioning/impl/errorhandling/MaintenanceExceptionHandler.java
provisioning/provisioning-impl/src/main/java/com/evolveum/midpoint/provisioning/impl/errorhandling/ObjectAlreadyExistHandler.java
provisioning/provisioning-impl/src/main/java/com/evolveum/midpoint/provisioning/impl/shadowmanager/ShadowManager.java
provisioning/provisioning-impl/src/main/java/com/evolveum/midpoint/provisioning/util/ProvisioningUtil.java
testing/story/src/test/java/com/evolveum/midpoint/testing/story/TestResourceInMaintenance.java
testing/story/src/test/resources/resource-in-maintenance/csv-resource1.xml
testing/story/src/test/resources/resource-in-maintenance/data-resource1.csv
testing/story/src/test/resources/resource-in-maintenance/shadow-user1.xml
testing/story/src/test/resources/resource-in-maintenance/user1.xml
testing/story/src/test/resources/resource-in-maintenance/user2.xml
testing/story/testng-integration.xml

Administrative operational state is set manually by midPoint users (e.g. administrator).
It signalizes whether resource is up and OPERATIONAL to receive provisioning requests or is down in MAINTENANCE and midPoint should not contact it during the provisioning.
This setting is useful when resource is e.g. undergoing planned maintenance to save computing time and error messages.
When under maintenance, operations are cached to the repository shadow and processed later when resource is back in OPERATIONAL mode.
EXPERIMENTAL FEATURE!

Resource administrative operational state (aka resource maintenance)

---

infra/axiom/src/main/antlr4/com/evolveum/axiom/lang/antlr/Axiom.g4
infra/axiom/src/main/java/com/evolveum/axiom/lang/antlr/AxiomAntlrStatementSource.java

Having SEP as a start of token leads to misleading item start pointer
when issuing diagnostic. Cleanup when separaterors are, and make sure
item starts with non-whitespace.
Signed-off-by: Robert Varga <robert.varga@pantheon.tech>

Fix axiom parser grammar

---

dist/src/main/bin/service.bat
tools/midpoint-war-layout/src/main/java/com/evolveum/midpoint/tools/layout/MidPointWarLauncher.java

This PR fixes https://jira.evolveum.com/browse/MID-6475 windows service script by utilizing the spring boot PropertiesLoader class   to start the application which redirects to the main class specified in META-INF. Additionally, the service.bat script uses the existing, but modified MidPointWarLauncher application to safely stop the application. 
It does not appear that the modified method is uses by any other method of stopping the application and it is believed that this change is safe.

Support 4.2 resolves MID-6475

---

infra/schema/src/main/resources/xml/ns/public/common/common-core-3.xsd
provisioning/ucf-impl-builtin/src/main/java/com/evolveum/midpoint/provisioning/ucf/impl/builtin/ManualConnectorInstance.java

Members of the organizations (direct only) or roles can be used as operators of manual applications - only org:default relation.
- It enables more robust and automated management of operators of individual manual resources.

Added support to insert a reference to an organization or a role into operatorRef.

---

infra/common/src/test/java/com/evolveum/midpoint/common/TestCryptoUtil.java
repo/system-init/src/main/java/com/evolveum/midpoint/init/ConfigurableProtectorFactory.java
repo/system-init/src/main/java/com/evolveum/midpoint/init/ProtectorConfiguration.java

This new option sacrifices little security to allow new scenarios when using hashed password storage. E.g. with fixed salt passive-cached credentials in ShadowTypes can be compared to password history in UserType as hashes for same password values are equivalent. New config.xml option keystore/fixedSalt need to be set to any arbitrary value and is used globally as single fixed salt for all hashed values in midPoint.
Dependency here: https://github.com/Evolveum/prism/pull/1

new config.xml option keystore/fixedSalt

---

gui/admin-gui/src/main/java/com/evolveum/midpoint/web/security/MidPointApplication.java
gui/admin-gui/src/main/java/com/evolveum/midpoint/web/security/WicketConfigurator.java
gui/admin-gui/src/main/java/com/evolveum/midpoint/web/security/WicketNoSerializationConfigurator.java

In MID-7135, serialization costs have been greatly reduced, but I have added an option to accept Wicket's feature limitation and choose the no-serialization mode for performance reason.
To use it, set the following in `$MP_HOME/application.properties`.
```
wicket.no-serialization.enabled=true
```
Enabling this mode will prevent the creation of serialized pages files under `$MP_HOME/Tomcat/localhost/midpoint/wicketFilestore/...`.
The maximum number of pages per session to be kept on-memory is also configurable (default is 1) with `wicket.no-serialization.max-pages`.

MID-7135 Add no-serialization option for Wicket

---

gui/admin-gui/src/main/java/com/evolveum/midpoint/gui/api/util/WebComponentUtil.java
gui/admin-gui/src/main/java/com/evolveum/midpoint/web/component/data/column/ColumnUtils.java
gui/admin-gui/src/main/java/com/evolveum/midpoint/web/component/prism/show/VisualizationItemValuePanel.java
model/model-impl/src/main/java/com/evolveum/midpoint/model/impl/visualizer/Visualizer.java
model/workflow-impl/src/main/java/com/evolveum/midpoint/wf/impl/processors/primary/policy/AssignmentPolicyAspectPart.java

https://jira.evolveum.com/browse/MID-8469
Fixed the following display format of the case/work item pages:
* The object, target and actor(s) are formatted with `displayName (name)` or `fullname (name)`. They are also clickable if exists.
* In the "View case work item" page, now the relation is translated (e.g. `[default]` => `[Member]` in english).
* The name of CaseType when assigning includes the relation. (Note: I didn't fix the target name in the text as `displayName (name)` because It is necessary to change `ObjectTypeUtil.createDisplayInformation` and it is used in many places and has some impact to fix)

MID-8469 Fixed display format of case/work item pages

---

infra/schema/pom.xml

This can avoid manual steps required when setting up in IDE such as vscode.

Add generated prism schema source to ide source path

---

model/authentication-api/src/main/java/com/evolveum/midpoint/authentication/api/AuthenticationChannel.java
model/authentication-api/src/main/java/com/evolveum/midpoint/authentication/api/evaluator/context/AbstractAuthenticationContext.java
model/authentication-impl/src/main/java/com/evolveum/midpoint/authentication/impl/FocusAuthenticationResultRecorder.java
model/authentication-impl/src/main/java/com/evolveum/midpoint/authentication/impl/authorization/evaluator/MidpointHttpAuthorizationEvaluator.java
model/authentication-impl/src/main/java/com/evolveum/midpoint/authentication/impl/channel/AuthenticationChannelImpl.java
model/authentication-impl/src/main/java/com/evolveum/midpoint/authentication/impl/channel/RestAuthenticationChannel.java
model/authentication-impl/src/main/java/com/evolveum/midpoint/authentication/impl/evaluator/AuthenticationEvaluatorImpl.java
model/authentication-impl/src/main/java/com/evolveum/midpoint/authentication/impl/provider/CorrelationProvider.java
model/authentication-impl/src/main/java/com/evolveum/midpoint/authentication/impl/provider/MidPointLdapAuthenticationProvider.java
model/authentication-impl/src/test/java/com/evolveum/midpoint/authentication/evaluator/TestAbstractAuthenticationEvaluator.java
model/model-api/src/main/java/com/evolveum/midpoint/model/api/authentication/GuiProfiledPrincipalManager.java
model/model-impl/src/main/java/com/evolveum/midpoint/model/impl/controller/AuthorizationDiagEvaluation.java
model/model-impl/src/main/java/com/evolveum/midpoint/model/impl/controller/ModelInteractionServiceImpl.java
model/model-impl/src/main/java/com/evolveum/midpoint/model/impl/security/GuiProfileCompiler.java
model/model-impl/src/main/java/com/evolveum/midpoint/model/impl/security/GuiProfiledPrincipalManagerImpl.java
model/model-intest/src/test/java/com/evolveum/midpoint/model/intest/security/TestSecurityPrincipal.java
model/model-test/src/main/java/com/evolveum/midpoint/model/test/AbstractModelIntegrationTest.java
repo/security-api/src/main/java/com/evolveum/midpoint/security/api/MidPointPrincipalManager.java
repo/security-enforcer-impl/src/main/java/com/evolveum/midpoint/security/enforcer/impl/SecurityEnforcerImpl.java
repo/security-impl/src/main/java/com/evolveum/midpoint/security/impl/SecurityContextManagerImpl.java
repo/security-impl/src/test/java/com/evolveum/midpoint/security/impl/MidPointPrincipalManagerMock.java

https://jira.evolveum.com/browse/MID-9062
Until now, GuiProfile compilation process has included not only Authorization resolution, but also GUI Config resolution. However, for operations that do not require GUI display, GUI Config resolution consume a lot of CPU in unnecessary processing (e.g., REST API authentication, script execution by runAsRef, etc.). Now, we have optimized the GUI Config resolution to be performed only when compiling GuiProfile that requires GUI display.

MID-9062 Optimized to compile GuiProfile

---

gui/admin-gui/src/main/java/com/evolveum/midpoint/web/component/data/LinkedReferencePanel.java
gui/admin-gui/src/main/java/com/evolveum/midpoint/web/component/data/column/ColumnUtils.java
gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/cases/CaseWorkItemsPanel.java
gui/admin-gui/src/main/java/com/evolveum/midpoint/web/page/admin/cases/PageCases.java

Impacted versions: 4.4, 4.8, master
Type: Bugfix/optimization
Resolving references on case pages especially for ShadowTypes cause slow page load, only names needed.
All cases page and others would timeout when resolving shadows for systems that required network fetch to gather information not necessary for page display.
Bugfix should be cherrypicked to support-4.4

Remove potentially expensive resolves

---

pom.xml

Similar to these two changes in later versions:
- https://github.com/Evolveum/midpoint/pull/219/commits/1ec9415f2dc518233954e390a8292c44318f83b4 (4.0.1 -> 4.0.4)
- https://github.com/Evolveum/midpoint/commit/0eff1cd01fc27e20fa6dadac3961e33e427e2fca (4.0.4 -> 4.0.5)
Solves vulnerabilities including: 
CVE-2024-28752
Critical
This is what the package maintainer tells us about this finding
A SSRF vulnerability using the Aegis DataBinding in versions of Apache CXF before 4.0.4, 3.6.3 and 3.5.8 allows an attacker to perform SSRF style attacks on webservices that take at least one parameter of any type. Users of other data bindings (including the default databinding) are not impacted.

Bump org.apache.cxf:cxf-rt-transports-http from 4.0.1 to 4.0.5

---

model/model-impl/src/main/java/com/evolveum/midpoint/model/impl/lens/PersonaProcessor.java

During a recompute task, midPoint set LazyAuditRequest in the lens context to avoid creating empty audit objects for every recomputation.
This change propagates the LazyAuditRequest property to the LensContext created for the persona delta execution. This will prevent midPoint from creating empty audit events for personas when running a recompute on the main user.

FIX: PersonaProcessor creates empty audit events on recompute task

---

model/model-impl/src/main/java/com/evolveum/midpoint/model/impl/trigger/CompletedTaskCleanupTriggerHandler.java
model/model-intest/src/test/java/com/evolveum/midpoint/model/intest/tasks/TestMiscTasks.java
model/model-intest/src/test/resources/tasks/misc/task-cleanup-subtasks-after-completion.xml

**What**
Remove not just root task, but also all its subtasks when it is cleaned-up.
**Why**
When cleanup after finish is set on task, it should be auto removed after specified duration from its completion.
However there was a bug, which caused, that only the root task was removed. If task run spawned any persistent subtasks (e.g. when number of workers per node is specified), those were not cleaned up. This change fixes it.

Fix cleanup after finish to remove also subtasks

---

model/model-impl/src/main/java/com/evolveum/midpoint/model/impl/trigger/CompletedTaskCleanupTriggerHandler.java
model/model-intest/src/test/java/com/evolveum/midpoint/model/intest/tasks/TestMiscTasks.java
model/model-intest/src/test/resources/tasks/misc/task-cleanup-subtasks-after-completion.xml

**What**
Remove not just the root task, but also all its subtasks when it is cleaned up.
**Why**
When cleanup after finish is set on task, it should be auto-removed after specified duration from its completion.
However there was a bug, which caused, that only the root task was removed. If task run spawned any persistent subtasks (e.g. when number of workers per node is specified), those were not cleaned up. This change fixes it.
---------
(cherry picked from commit 4da3d2184cce9dfa7d066dd750d5e7725ac65865)

Fix cleanup after finish to remove also subtasks (#238)

---

pom.xml

**What**
Remove comment saying that after
`mvn clean install -P -dist -DskipTests` you can find built `midPoint.jar` in target of `gui/midpoint-jar` module, because that is not true anymore.

Remove comment which is not true anymore

---

model/model-impl/src/main/java/com/evolveum/midpoint/model/impl/controller/SchemaTransformer.java
model/model-impl/src/main/java/com/evolveum/midpoint/model/impl/controller/transformer/DataAccessProcessor.java
model/model-impl/src/main/java/com/evolveum/midpoint/model/impl/lens/LensContext.java
model/model-intest/src/test/java/com/evolveum/midpoint/model/intest/security/AbstractInitializedSecurityTest.java
model/model-intest/src/test/java/com/evolveum/midpoint/model/intest/security/TestSecurityBasic.java
model/model-intest/src/test/resources/security/role-user-add-read-some.xml
release-notes.adoc

**What**
Fix an error caused by change of immutable object (in this case immutable delta), which happens during preview of "create role" changes. But it could potentially happen during any "create" operation.
**Notes**
This error could be fixed in various ways. Some of considered solutions:
- Add `modifyEachObject` and `modifyEachDelta` methods to `ElementState` and to `LensElementContext`. These methods would allow to modify internal deltas/objects by internally cloning them if they are immutable.
- Cloning whole `LensContext` before passing it to the `SchemaTransformer` for application of security constraints.
- Cloning `LensFocusContext` and `LensProjectionContext` before passing them to the `DataAccessProcessor`.
It's important to say, that **none** from mentioned solutions is very …

Fix change of immutable object caused by preview

---

release-notes.adoc
repo/system-init/src/main/resources/initial-objects/value-policy/010-value-policy.xml

**What**
Remove constraint on maximum password length from default configuration.
**Why**
It basically goes against our documented best practice. The limitation was there because of the defaults in some external systems (AD). However we should not relent on the security just because of external systems default policies, thus this change removes the constraint.
**Fixes**: MID-10305

Remove max password length constraint

---

docs/interfaces/rest/operations/raw/operation-prop-search.adoc
model/rest-impl/src/main/java/com/evolveum/midpoint/rest/impl/ModelRestController.java
release-notes.adoc

**What**
Allow user to exclude metadata from specified paths
**Why**
So far use could exclude normal data, but not metadata even though documentation contained examples also with metadata exclusion. Now metadata exclusion is supported as well.
**Fixes**: MID-10216
(cherry picked from commit 2dfbce298b6ae455c8d9359b027ef273a8e3afd1)

Support metadata exclusion in REST get/search APIs

---

model/rest-impl/src/main/java/com/evolveum/midpoint/rest/impl/ModelRestController.java

**What**
Fix NPEs caused by missing `exclude` parameter in some get/search endpoints.
**Fixes:** MID-10216
(cherry picked from commit 5d531fa0574570f4c3c175f11dd9e949a32684dc)

Fix REST APIs when exclude parameter is not present

---

release-notes.adoc
repo/repo-cache/src/test/java/com/evolveum/midpoint/repo/cache/TestRepositoryCache.java

**Why**
Page size which were originally assumed wasn't correct anymore and it caused that the size limit of heap which was tested in heap usage test **may** not be big enough (for example on my system the test fails, but on our test infra it passes).
**Relates to**: MID-10048
(cherry picked from commit 8c7208da5081b04e947ee1cb51fe79307db358d2)

Change assumed size of page in repository cache test

---

repo/repo-cache/src/main/java/com/evolveum/midpoint/repo/cache/invalidation/ChangeDescription.java

**Why**
Catching `Throwable` to "catch them all" is a bad practice, because it catches also `Error`'s which in general, should not be catched, because you "usuealy" can not do anything with them.

Don't use `Throwable` in `catch` statement

---

gui/admin-gui/src/main/java/com/evolveum/midpoint/gui/api/component/wizard/BasicWizardStepPanel.html
gui/admin-gui/src/main/java/com/evolveum/midpoint/gui/api/component/wizard/BasicWizardStepPanel.java
gui/admin-gui/src/main/java/com/evolveum/midpoint/gui/impl/component/wizard/AbstractWizardStepPanel.java
gui/admin-gui/src/main/java/com/evolveum/midpoint/gui/impl/page/admin/schema/component/BasicDefinitionPanel.java
gui/admin-gui/src/main/java/com/evolveum/midpoint/web/component/util/VisibleEnableBehaviour.java
release-notes.adoc

**What**
Fix the issue where the top part of the button on schema edit wizard popup was not clickable.
**Notes**
The problem was caused by the `mb-n5` css class set on the top `div` in modal body:
```html
<div class="modal-body" id="id16c">
<div class="mt-n4 mb-n5"> 
```
It was set in the `BasicDefinitionPanel` and it looks like that class was added to the `div` to compensate the `mt-5` class in an underlying `div` with usual (in this case hidden) wizard buttons (next, back, exit, submit) which is defined in `BasicWizardStepPanel` and its `BasicWizardStepPanel.html` HTML file.
```html
<div class="d-flex gap-3 justify-content-center mt-5"> 
<a id="id1dd" hidden="" data-wicket-placeholder=""></a>
<a id="id1de" hidden="" data-wicket-placeholder=""></a>
<a id="id1df" hidden="" …
```

Fix non clickable part of button

---

docs/roles-policies/certification/index.adoc

**What**
Add few paragraphs about terms like certification case, campaign stage and campaign reiteration.
**Why**
Those terms were mentioned on several places in certification docs, but there was no basic explanation of what those terms means.

Add more info to Access Certifications docs

---

docs/diag/performance.adoc
infra/schema/src/main/java/com/evolveum/midpoint/schema/util/CertCampaignTypeUtil.java
infra/schema/src/main/java/com/evolveum/midpoint/schema/util/cases/WorkItemTypeUtil.java
model/certification-impl/src/main/java/com/evolveum/midpoint/certification/impl/AccCertQueryHelper.java
model/certification-impl/src/main/java/com/evolveum/midpoint/certification/impl/AccCertUpdateHelper.java
model/certification-impl/src/main/java/com/evolveum/midpoint/certification/impl/task/AccessCertificationStageManagementRun.java
model/certification-impl/src/test/java/com/evolveum/midpoint/certification/test/AbstractCertificationTest.java
model/certification-impl/src/test/java/com/evolveum/midpoint/certification/test/AccessCertificationEventListenerStub.java
model/certification-impl/src/test/java/com/evolveum/midpoint/certification/test/TestCertificationBasic.java
model/certification-impl/src/test/java/com/evolveum/midpoint/certification/test/TestCertificationNotifications.java
model/certification-impl/src/test/java/com/evolveum/midpoint/certification/test/TestEscalation.java
model/certification-impl/src/test/java/com/evolveum/midpoint/certification/test/TestManualEscalation.java
model/certification-impl/src/test/resources/common/certification-of-eroot-user-assignments-notifications.xml
model/certification-impl/src/test/resources/common/user-bob.xml
release-notes.adoc

**What**
Optimize and simplify the queries (and code) used to select reviewers who should receive "required review" notifications.
**Why**
The previous implementation tended to cause opening of certification campaign stages to hang indefinitely\*. These freezes seem to be caused by a large number of inserts followed by more complex select.
It looks like rapid inserts causes need for the DB to do vacuum/analyze operations, but those operations are run periodically with certain delay. If the select operation hits the DB before the "autovacuuming" period (called nap time) elapses, it may appear to freeze\* in the DB without any sign of real activity.
Lowering the "autovacuum nap time" configuration option seems to mitigate this issue. By default, this option is set to 1 minute. During local …

Optimize reviewer notifications from certification

---

model/rest-impl/src/main/java/com/evolveum/midpoint/rest/impl/AbstractRestController.java
model/rest-impl/src/main/java/com/evolveum/midpoint/rest/impl/ModelRestController.java

For my use case i need to have total object count information as a part of search response. For this reason i modified existing code to return total count value in X-Total-Count header.
**Example:**
If there are 2 records with name that starts with "0", request like this
```
POST http://localhost:8080/midpoint/ws/rest/users/search?options=resolveNames&returnTotalCount=true
BODY
{
"query": {
"filter": {
"text": "name startsWith '0'"
},
"paging": {
"orderBy": "name",
"orderDirection": "ascending",
"offset": "0",
"maxSize": "1"
}
}
}
```
..should result with response containing 1 record in body with total count of filtered users in header with value 2.
Let me know if you want me to additionally change or add something.
Best regards

Returning total object count through X-Total-Count header when calling search REST endpoint

---

docs/admin-gui/resource-wizard/object-type/index.adoc

Update the start of the tutorial to account also for cases when a user comes with an existing object type and wants to edit it; also moved the callout/mention of filtering to its own section because it's a rather important topic. A (related) shadow reclassification guide is TBD at this point.

Add mention of editing existing objType; convert filtering into section

---

docs/tasks/synchronization-tasks/import-and-reconciliation/gui.adoc

I slightly remade the GUI guide to make it useable for all the 3
possible task kinds available when creating tasks from the account list.
This makes it possible to use one article for more scenarios rather than
create multiple articles with lots of reused / duplicate content.

Make the GUIde universal for all 3 task kinds

---

docs/admin-gui/resource-wizard/configuration-resource-panels.adoc
docs/admin-gui/resource-wizard/create-resource-using-wizard.adoc
docs/admin-gui/resource-wizard/limitation-all.adoc
docs/admin-gui/resource-wizard/object-type/activation/index.adoc
docs/admin-gui/resource-wizard/object-type/credentials/index.adoc
docs/admin-gui/resource-wizard/object-type/index.adoc
docs/admin-gui/resource-wizard/object-type/mapping/index.adoc
docs/admin-gui/resource-wizard/object-type/policies/index.adoc
docs/admin-gui/resource-wizard/object-type/synchronization/index.adoc
docs/admin-gui/resource-wizard/see-also.adoc
docs/tasks/synchronization-tasks/import-and-reconciliation/gui.adoc

This PR encompasses multiple loosely related changes: I updated the
Task GUIde with task naming examples and changed one wording to reflect
the GUIde is no longer about import tasks only (done in
3c411cf524b4b472007f21961f832076cee7ddf6 ). Furthermore, I removed
includes of the configuration panels and lifecycle summary in the
resource object wizard GUIdes because they are superfluous and
distracting. Instead, I linked the relevant articles. Lastly, I polished
the limitations-all.adoc and used that one in all the resource wizard
articles (except for correlation which is handles in another branch
currently) to make the limitations easier to manage, among other things.

Various improvements to resource wizard and sync task GUIdes

---

docs/tasks/synchronization-tasks/import-and-reconciliation/gui.adoc

sync with changes done in 4.9 and master in 10cb8a92bac3cde27e992769dad3962f46c67fe4

add task nameing examples + remove superfluous scenario example

---

docs/admin-gui/resource-wizard/object-type/mapping/advanced-mappings.adoc
docs/admin-gui/resource-wizard/object-type/mapping/index.adoc

The word "icon" replaced with "button", and added non-breaking spaces between icon and button names.

remove the word icon and use nonbreaking spaces
